[package]
name = "{{project_name}}"
version = "0.1.0"
edition = "2024"

[dependencies] 
sfx = "0.1.0" 
ctor = "0.4.0"
once_cell = "1.17"
tokio = { version = "1", features = ["full"] }
sha2 = "0.10.8" 
tracing = "0.1.41" 
